### ISSUE TITLE
Bug while changing to dark theme

### ISSUE THREAD

**Issue by Keycard755** [DHD2280/Oxygen-Customizer#42]
### Describe the bug

Details:
![Screenshot_2024-08-19-14-18-01-18_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/a79b81e4-a2a6-4023-b742-b3b121a2c7c2)
So the issue is while I turn dark mode it won't apply the circle like this:
Without dark mode :
![Screenshot_2024-08-19-14-19-08-71_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/a4cd8c5e-9bbb-4705-b183-e9bf81dddee3)
With dark mode: 
![Screenshot_2024-08-19-14-19-36-53_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/fb8f30c7-ec56-463d-a117-243b943a9080)

Adds: can you add the cutomization for wallpapers to like the theme store have some limited one and I don't like that so can you add some including lock screen

Bugs: first is the dark mode issue 
Then the music pulse is not working for me 

### Steps to reproduce

don't have idea 

### Expected behavior

Soo after the dark mode it also should have made the notification panel oval

### Device information

- Device: [e.g. OnePlus Nord ce 2 ]
Build number

IV2201_11_F.52

Baseband version

M_V3_P10,M_V3_P10

Kernel version

4.19.191+

**Comment by DHD2280** [comment]
Hello.
This happens on OOS13 and I couldn't find a fix.
The problem is that I can't support every tweak even on OOS13.
The bug is that on dark mode, notification styles won't apply.

Also Pulse, Depth Wallpaper and Album Art on Lockscreen won't work in OOS13.

I'm sorry about that, but as I said, I can't support everything even on OOS13, since I started working on OOS14.
